name: Lovisas workflow

on:
  workflow_dispatch:
    inputs: 
      show_message:
        description: "Log errors if tests fails"
        required: true
        default: "false"
        type: boolean

jobs:
  error_log:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Installera 'requests' direkt här

      - name: Run API test script
        run: |
          python test_main.py

      - name: Failing step if show_message is 'false'
        run: |
          echo "Error has occurd" > error.log
          exit 1
        if: ${{ github.event.inputs.show_message == 'false' }}

      - name: Upload error log
        if: failure()
        uses: actions/upload-artifact@v3
        with: 
          name: error-log
          path: error.log

