name: Lovisas workflow

on:
  workflow_dispatch:
    inputs: 
      show_message:
        description: "Run without errors"
        required: false
        default: true
        type: boolean

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        id: pytest
        run: |
          pytest test_main.py || true  # Se till att processen inte misslyckas direkt om testerna misslyckas

      - name: Generate error log
        if: failure() || github.event.inputs.show_message == 'true'
        run: |
          echo "Error log generated due to test failure or user request." > error.log
          pytest test_main.py >> error.log || true  # Lägg till testerna i loggen (komplett logg)

      - name: Upload error log
        if: always() && (failure() || github.event.inputs.show_message == 'true')
        uses: actions/upload-artifact@v3
        with: 
          name: error-log
          path: error.log

  docker_build:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t devopsimage .

      - name: Tag Docker Image
        run: |
          docker tag devopsimage "${{ secrets.DOCKER_USERNAME }}/devopsimage:latest"

      - name: Push Docker Image
        run: |
          docker push "${{ secrets.DOCKER_USERNAME }}/devopsimage:latest"
