name: Lovisas workflow

on:
  workflow_dispatch:
    inputs: 
      show_message:
        description: "Run without errors"
        required: false
        default: true
        type: boolean

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Failing step if show_message is 'false'
        run: |
          echo "Error has occurred" > error.log
          exit 1
        if: ${{ github.event.inputs.show_message == 'false' }}

      - name: Upload error log
        if: failure()
        uses: actions/upload-artifact@v3
        with: 
          name: error-log
          path: error.log

  docker_build:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t devopsimage .

      - name: Push Docker Image
        run: |
          docker tag myapp-image ${{ secrets.DOCKER_USERNAME }}/devopsimage:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/devopsimage:latest
