name: Lovisas workflow

on:
  workflow_dispatch:
    inputs: 
      show_message:
        description: "Run without errors"
        required: false
        default: true
        type: boolean

jobs:
  error_log:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Installera alla beroenden från requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Failing step if show_message is 'false'
        run: |
          echo "Error has occurred" > error.log
          exit 1  # Avsluta med fel om show_message är false
        if: ${{ github.event.inputs.show_message == 'false' }}

      - name: Upload error log
        if: failure() 
        uses: actions/upload-artifact@v3
        with: 
          name: error-log
          path: error.log
